# fly.toml app configuration file generated for scamview on 2024-09-24T01:21:49+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'scamview'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
