# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  echo:
    name: Echo secrets
    runs-on: ubuntu-latest
    steps:
      - run: echo $SUPABASE_KEY
      - run: echo $SUPABASE_URL
    env:
      SUPABASE_KEY: ${{ vars.SUPABASE_KEY }}
      SUPABASE_URL: ${{ vars.SUPABASE_URL }}
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --env NEXT_PUBLIC_SUPABASE_ANON_KEY=$SUPABASE_KEY --env NEXT_PUBLIC_SUPABASE_URL=$SUPABASE_URL
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          SUPABASE_KEY: ${{ vars.SUPABASE_KEY }}
          SUPABASE_URL: ${{ vars.SUPABASE_URL }}